name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate json file
        run: python3 .github/workflows/generate-list.py
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automatic generation of the file list.xml"
          git push
          curl https://img.papamica.com/pull.php
